# Generated by Django 3.1.2 on 2021-05-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataform',
            name='date',
            field=models.DateField(),
        ),
    ]
