# Generated by Django 3.1.2 on 2021-05-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0002_auto_20210521_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataform',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
